import Head from 'next/head'
//import Image from 'next/image'
//import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div>
      <Head>
        <title>CodeWear.com -Wear the Code</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
  <div className="font-bold text-center">
    hello
    
  </div>
    </div>
  )
}
