import Head from 'next/head'
import Navbar from '../components/Navbar'
import Footer from '../components/Footer'
import Image from 'next/image'
//import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div>
      <Head>
        <title>CodeWear.com -Wear the Code</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo-modified.png" />
      </Head>
      <Navbar/>
      <Image src="/head.png" alt="" height={600} width={1500}/>

      <Footer/>
    </div>
  )
}
